### ISSUE TITLE
Applying towards other finned species

### ISSUE THREAD

**Issue by parallelo** [ChristianBergler/FIN-PRINT#2]
Hi Christian!  Your paper for FIN-PRINT was super interesting.  Excellent work.

I'm investigating possibilities for some applied conservation work, and looking into the field of individual visual identification within a species.  Just curious if you have any insight on whether your work could be applied to other species, if trained on new data (perhaps using transfer learning).  In particular, I'm interested in a few specific dolphin (Bottlenose, Common & Striped) and whale (Fin) species in the Mediterranean.  

Do you see any gotchas there?  Any insight or pointers would be much appreciated.  

Thanks and best wishes from Colorado,

Jeff

PS - I'm also reading your audio identification papers now too.  Lots of interesting research.

**Comment by ChristianBergler** [comment]
Hi Jeff,
thanks for your kind words! Yes FIN-PRINT can be transferred to any species which can be identified by some unique visual natural markings. We are currently applying the software to bird species, for example. We also have currently some ongoing work on dolphin identification as well. So, to summarize: yes, it is possible to transfer basically the entire pipeline (detection, extraction, identification) to other species.

So in case if you have more specific questions you can contact me via mail as well, no problem!

Thanks a lot!

Take care,
Christian

**Comment by parallelo** [comment]
Hi Christian.  Thanks for the info!  Makes sense.  I'll reach out via email.
